#ifndef _UI_MSG_CODE_H
#define _UI_MSG_CODE_H


enum {
    UI_MSG_CODE_COMM = 0,
    UI_MSG_CODE_BATTERY_PERCENT,
    UI_MSG_CODE_CHARGING,
    UI_MSG_CODE_WIFI,
    UI_MSG_CODE_FILE_SYSTEM_REFRESH,
    UI_MSG_CODE_LORA_CHAT_ITEM,
};


#endif
