#ifndef _UI_MSG_CODE_H
#define _UI_MSG_CODE_H


enum {
    UI_MSG_CODE_COMM = 0,
    UI_MSG_CODE_REFRESH_TILES,
    UI_MSG_CODE_FAIL,
    UI_MSG_CODE_LED,
    UI_MSG_CODE_LOADED,
    UI_MSG_CODE_SAVED,
    UI_MSG_CODE_CHANGED,
    UI_MSG_CODE_FILE_SYSTEM_REFRESH,
    UI_MSG_CODE_UPDATE_FIRMWARE_PROGRESS,
    UI_MSG_CODE_UPDATE_FIRMWARE_DONE,
    UI_MSG_CODE_UPDATE_FIRMWARE_SUCCESS,
};


#endif
