#ifndef _FLASH_MAP_H
#define _FLASH_MAP_H

//SPI FLASH ADDR

//FATFS, 800kB

#define FATFS_FLASH_SECTOR_SIZE             4096
#define FATFS_FLASH_SECTOR_COUNT            200

//DEVICE SETTINGS, 4KB
#define FLASH_ADDR_DEVICE_SETTINGS          (FATFS_FLASH_SECTOR_SIZE * FATFS_FLASH_SECTOR_COUNT)
#define FLASH_SIZE_DEVICE_SETTINGS          0x1000

//ERROR INFO, 4KB
#define SPI_FLASH_ADDR_ERR_INFO             (FLASH_ADDR_DEVICE_SETTINGS + FLASH_SIZE_DEVICE_SETTINGS)
#define SPI_FLASH_SIZE_ERR_INFO             0x1000


#endif

